export enum ErrorCode {
  // Resource
  INVALID_ID = 'INVALID_ID',
  RESOURCE_NOT_FOUND = 'RESOURCE_NOT_FOUND',
  TOOL_NOT_FOUND = 'TOOL_NOT_FOUND',
  USER_NOT_FOUND = 'USER_NOT_FOUND',
  DUPLICATE_ENTRY = 'DUPLICATE_ENTRY',

  // Auth
  EMAIL_ALREADY_REGISTERED = 'EMAIL_ALREADY_REGISTERED',
  INVALID_CREDENTIALS = 'INVALID_CREDENTIALS',
  NO_TOKEN_PROVIDED = 'NO_TOKEN_PROVIDED',
  INVALID_EXPIRED_TOKEN = 'INVALID_EXPIRED_TOKEN',
  UNAUTHORIZED = 'UNAUTHORIZED',

  // Upvotes
  ALREADY_UPVOTED = 'ALREADY_UPVOTED',
  NOT_UPVOTED = 'NOT_UPVOTED',

  // Tools
  TOOL_ALREADY_EXISTS = 'TOOL_ALREADY_EXISTS',

  // Validation
  VALIDATION_ERROR = 'VALIDATION_ERROR',

  // Server
  INTERNAL_SERVER_ERROR = 'INTERNAL_SERVER_ERROR',
  NOT_FOUND = 'NOT_FOUND',
}
